import sharp from 'sharp';
import { put } from '@vercel/blob';

/**
 * Upload buffer to Vercel Blob and return public URL
 */
async function uploadToBlob(buffer: Buffer, filename: string): Promise<string> {
  try {
    const blob = await put(filename, buffer, {
      access: 'public',
      contentType: 'image/png',
    });
    return blob.url;
  } catch (error) {
    console.error('Error uploading to Vercel Blob:', error);
    throw new Error('Failed to upload image to Vercel Blob');
  }
}

/**
 * Convert SVG string to PNG and upload to Vercel Blob
 */
export async function svgToPng(svgString: string): Promise<string> {
  try {
    // Use sharp to convert SVG to PNG
    const pngBuffer = await sharp(Buffer.from(svgString))
      .png()
      .toBuffer();

    // Upload to Vercel Blob
    const filename = `svg-${Date.now()}-${Math.random().toString(36).slice(2)}.png`;
    return await uploadToBlob(pngBuffer, filename);
  } catch (error) {
    console.error('Error converting SVG to PNG:', error);
    throw new Error('Failed to convert SVG to PNG');
  }
}

/**
 * Convert ASCII art to PNG and upload to Vercel Blob
 * This creates an SVG from the ASCII text and then converts to PNG
 */
export async function asciiToPng(asciiArt: string): Promise<string> {
  try {
    // Prepare the ASCII text for SVG
    const lines = asciiArt.split('\n');
    const maxLineLength = Math.max(...lines.map(line => line.length));
    const fontSize = 14;
    const charWidth = fontSize * 0.6; // Monospace approximation
    const lineHeight = fontSize * 1.3;

    const width = Math.ceil(maxLineLength * charWidth) + 40;
    const height = Math.ceil(lines.length * lineHeight) + 40;

    // Escape XML special characters
    const escapeXml = (str: string) =>
      str.replace(/&/g, '&amp;')
         .replace(/</g, '&lt;')
         .replace(/>/g, '&gt;')
         .replace(/"/g, '&quot;')
         .replace(/'/g, '&apos;');

    // Create SVG with ASCII art
    const svgLines = lines.map((line, index) => {
      const y = 20 + (index * lineHeight);
      return `<text x="20" y="${y}" font-family="monospace" font-size="${fontSize}" fill="#00FF00">${escapeXml(line)}</text>`;
    }).join('\n    ');

    const svg = `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
  <rect width="100%" height="100%" fill="#000000"/>
  <g>
    ${svgLines}
  </g>
</svg>`;

    // Convert SVG to PNG
    const pngBuffer = await sharp(Buffer.from(svg))
      .png()
      .toBuffer();

    // Upload to Vercel Blob
    const filename = `ascii-${Date.now()}-${Math.random().toString(36).slice(2)}.png`;
    return await uploadToBlob(pngBuffer, filename);
  } catch (error) {
    console.error('Error converting ASCII to PNG:', error);
    throw new Error('Failed to convert ASCII to PNG');
  }
}

/**
 * Validate SVG string
 */
export function isValidSvg(svgString: string): boolean {
  const trimmed = svgString.trim();
  return trimmed.startsWith('<svg') && trimmed.includes('</svg>');
}

/**
 * Validate ASCII art (basic check)
 */
export function isValidAscii(asciiString: string): boolean {
  // Check if it's not empty and has multiple lines
  const lines = asciiString.trim().split('\n');
  return lines.length > 0 && asciiString.length > 10;
}

/**
 * Upload base64 image directly to Vercel Blob
 * For images generated by agents (OpenAI, Gemini, etc.)
 */
export async function uploadBase64Image(base64String: string): Promise<string> {
  try {
    // Remove data URL prefix if present (e.g., "data:image/png;base64,")
    const base64Data = base64String.replace(/^data:image\/\w+;base64,/, '');

    // Convert base64 to buffer
    const buffer = Buffer.from(base64Data, 'base64');

    // Optimize image with sharp (resize if too large, compress)
    const optimizedBuffer = await sharp(buffer)
      .resize(2048, 2048, {
        fit: 'inside',
        withoutEnlargement: true
      })
      .png({ quality: 90 })
      .toBuffer();

    // Upload to Vercel Blob
    const filename = `generated-${Date.now()}-${Math.random().toString(36).slice(2)}.png`;
    return await uploadToBlob(optimizedBuffer, filename);
  } catch (error) {
    console.error('Error uploading base64 image:', error);
    throw new Error('Failed to upload base64 image');
  }
}
